import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>notes</title>
      </head>
      <body className='bg-slate-950'> 
        <header>
          <nav>
            <h1 className='text-3xl font-bold text-slate-100 m-4'>notes</h1>
          </nav>
          </header>  
          <main>
            {children}
          </main>
        </body>
    </html>
  )
}
